kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: calico
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    protocol: TCP
  - containerPort: 32443
    hostPort: 443
    protocol: TCP
  - containerPort: 35443  # Calico's Typha port
    hostPort: 5443
    protocol: TCP
networking:
  disableDefaultCNI: true # disable kindnet
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet

